export const TEAMS = [
  // NFL — AFC East
  { name: 'Buffalo Bills', league: 'NFL', division: 'AFC East', id: 2 },
  { name: 'Miami Dolphins', league: 'NFL', division: 'AFC East', id: 15 },
  { name: 'New England Patriots', league: 'NFL', division: 'AFC East', id: 17 },
  { name: 'New York Jets', league: 'NFL', division: 'AFC East', id: 20 },
  // NFL — AFC North
  { name: 'Baltimore Ravens', league: 'NFL', division: 'AFC North', id: 33 },
  { name: 'Cincinnati Bengals', league: 'NFL', division: 'AFC North', id: 4 },
  { name: 'Cleveland Browns', league: 'NFL', division: 'AFC North', id: 5 },
  { name: 'Pittsburgh Steelers', league: 'NFL', division: 'AFC North', id: 23 },
  // NFL — AFC South
  { name: 'Houston Texans', league: 'NFL', division: 'AFC South', id: 34 },
  { name: 'Indianapolis Colts', league: 'NFL', division: 'AFC South', id: 11 },
  { name: 'Jacksonville Jaguars', league: 'NFL', division: 'AFC South', id: 30 },
  { name: 'Tennessee Titans', league: 'NFL', division: 'AFC South', id: 10 },
  // NFL — AFC West
  { name: 'Denver Broncos', league: 'NFL', division: 'AFC West', id: 7 },
  { name: 'Kansas City Chiefs', league: 'NFL', division: 'AFC West', id: 12 },
  { name: 'Las Vegas Raiders', league: 'NFL', division: 'AFC West', id: 13 },
  { name: 'Los Angeles Chargers', league: 'NFL', division: 'AFC West', id: 24 },
  // NFL — NFC East
  { name: 'Dallas Cowboys', league: 'NFL', division: 'NFC East', id: 6 },
  { name: 'New York Giants', league: 'NFL', division: 'NFC East', id: 19 },
  { name: 'Philadelphia Eagles', league: 'NFL', division: 'NFC East', id: 21 },
  { name: 'Washington Commanders', league: 'NFL', division: 'NFC East', id: 28 },
  // NFL — NFC North
  { name: 'Chicago Bears', league: 'NFL', division: 'NFC North', id: 3 },
  { name: 'Detroit Lions', league: 'NFL', division: 'NFC North', id: 8 },
  { name: 'Green Bay Packers', league: 'NFL', division: 'NFC North', id: 9 },
  { name: 'Minnesota Vikings', league: 'NFL', division: 'NFC North', id: 16 },
  // NFL — NFC South
  { name: 'Atlanta Falcons', league: 'NFL', division: 'NFC South', id: 1 },
  { name: 'Carolina Panthers', league: 'NFL', division: 'NFC South', id: 29 },
  { name: 'New Orleans Saints', league: 'NFL', division: 'NFC South', id: 18 },
  { name: 'Tampa Bay Buccaneers', league: 'NFL', division: 'NFC South', id: 27 },
  // NFL — NFC West
  { name: 'Arizona Cardinals', league: 'NFL', division: 'NFC West', id: 22 },
  { name: 'Los Angeles Rams', league: 'NFL', division: 'NFC West', id: 14 },
  { name: 'San Francisco 49ers', league: 'NFL', division: 'NFC West', id: 25 },
  { name: 'Seattle Seahawks', league: 'NFL', division: 'NFC West', id: 26 },
  // NBA — Atlantic
  { name: 'Boston Celtics', league: 'NBA', division: 'Atlantic', id: 2 },
  { name: 'Brooklyn Nets', league: 'NBA', division: 'Atlantic', id: 17 },
  { name: 'New York Knicks', league: 'NBA', division: 'Atlantic', id: 18 },
  { name: 'Philadelphia 76ers', league: 'NBA', division: 'Atlantic', id: 20 },
  { name: 'Toronto Raptors', league: 'NBA', division: 'Atlantic', id: 28 },
  // NBA — Central
  { name: 'Chicago Bulls', league: 'NBA', division: 'Central', id: 4 },
  { name: 'Cleveland Cavaliers', league: 'NBA', division: 'Central', id: 5 },
  { name: 'Detroit Pistons', league: 'NBA', division: 'Central', id: 8 },
  { name: 'Indiana Pacers', league: 'NBA', division: 'Central', id: 11 },
  { name: 'Milwaukee Bucks', league: 'NBA', division: 'Central', id: 15 },
  // NBA — Southeast
  { name: 'Atlanta Hawks', league: 'NBA', division: 'Southeast', id: 1 },
  { name: 'Charlotte Hornets', league: 'NBA', division: 'Southeast', id: 30 },
  { name: 'Miami Heat', league: 'NBA', division: 'Southeast', id: 14 },
  { name: 'Orlando Magic', league: 'NBA', division: 'Southeast', id: 19 },
  { name: 'Washington Wizards', league: 'NBA', division: 'Southeast', id: 27 },
  // NBA — Northwest
  { name: 'Denver Nuggets', league: 'NBA', division: 'Northwest', id: 7 },
  { name: 'Minnesota Timberwolves', league: 'NBA', division: 'Northwest', id: 16 },
  { name: 'Oklahoma City Thunder', league: 'NBA', division: 'Northwest', id: 25 },
  { name: 'Portland Trail Blazers', league: 'NBA', division: 'Northwest', id: 22 },
  { name: 'Utah Jazz', league: 'NBA', division: 'Northwest', id: 26 },
  // NBA — Pacific
  { name: 'Golden State Warriors', league: 'NBA', division: 'Pacific', id: 9 },
  { name: 'LA Clippers', league: 'NBA', division: 'Pacific', id: 12 },
  { name: 'Los Angeles Lakers', league: 'NBA', division: 'Pacific', id: 13 },
  { name: 'Phoenix Suns', league: 'NBA', division: 'Pacific', id: 21 },
  { name: 'Sacramento Kings', league: 'NBA', division: 'Pacific', id: 23 },
  // NBA — Southwest
  { name: 'Dallas Mavericks', league: 'NBA', division: 'Southwest', id: 6 },
  { name: 'Houston Rockets', league: 'NBA', division: 'Southwest', id: 10 },
  { name: 'Memphis Grizzlies', league: 'NBA', division: 'Southwest', id: 29 },
  { name: 'New Orleans Pelicans', league: 'NBA', division: 'Southwest', id: 3 },
  { name: 'San Antonio Spurs', league: 'NBA', division: 'Southwest', id: 24 },
  // MLB — AL East
  { name: 'Baltimore Orioles', league: 'MLB', division: 'AL East', id: 1 },
  { name: 'Boston Red Sox', league: 'MLB', division: 'AL East', id: 2 },
  { name: 'New York Yankees', league: 'MLB', division: 'AL East', id: 10 },
  { name: 'Tampa Bay Rays', league: 'MLB', division: 'AL East', id: 30 },
  { name: 'Toronto Blue Jays', league: 'MLB', division: 'AL East', id: 14 },
  // MLB — AL Central
  { name: 'Chicago White Sox', league: 'MLB', division: 'AL Central', id: 4 },
  { name: 'Cleveland Guardians', league: 'MLB', division: 'AL Central', id: 5 },
  { name: 'Detroit Tigers', league: 'MLB', division: 'AL Central', id: 6 },
  { name: 'Kansas City Royals', league: 'MLB', division: 'AL Central', id: 7 },
  { name: 'Minnesota Twins', league: 'MLB', division: 'AL Central', id: 9 },
  // MLB — AL West
  { name: 'Athletics', league: 'MLB', division: 'AL West', id: 11 },
  { name: 'Houston Astros', league: 'MLB', division: 'AL West', id: 18 },
  { name: 'Los Angeles Angels', league: 'MLB', division: 'AL West', id: 3 },
  { name: 'Seattle Mariners', league: 'MLB', division: 'AL West', id: 12 },
  { name: 'Texas Rangers', league: 'MLB', division: 'AL West', id: 13 },
  // MLB — NL East
  { name: 'Atlanta Braves', league: 'MLB', division: 'NL East', id: 15 },
  { name: 'Miami Marlins', league: 'MLB', division: 'NL East', id: 28 },
  { name: 'New York Mets', league: 'MLB', division: 'NL East', id: 21 },
  { name: 'Philadelphia Phillies', league: 'MLB', division: 'NL East', id: 22 },
  { name: 'Washington Nationals', league: 'MLB', division: 'NL East', id: 20 },
  // MLB — NL Central
  { name: 'Chicago Cubs', league: 'MLB', division: 'NL Central', id: 16 },
  { name: 'Cincinnati Reds', league: 'MLB', division: 'NL Central', id: 17 },
  { name: 'Milwaukee Brewers', league: 'MLB', division: 'NL Central', id: 8 },
  { name: 'Pittsburgh Pirates', league: 'MLB', division: 'NL Central', id: 23 },
  { name: 'St. Louis Cardinals', league: 'MLB', division: 'NL Central', id: 24 },
  // MLB — NL West
  { name: 'Arizona Diamondbacks', league: 'MLB', division: 'NL West', id: 29 },
  { name: 'Colorado Rockies', league: 'MLB', division: 'NL West', id: 27 },
  { name: 'Los Angeles Dodgers', league: 'MLB', division: 'NL West', id: 19 },
  { name: 'San Diego Padres', league: 'MLB', division: 'NL West', id: 25 },
  { name: 'San Francisco Giants', league: 'MLB', division: 'NL West', id: 26 },
  // NHL — Atlantic
  { name: 'Boston Bruins', league: 'NHL', division: 'Atlantic', id: 1 },
  { name: 'Buffalo Sabres', league: 'NHL', division: 'Atlantic', id: 2 },
  { name: 'Detroit Red Wings', league: 'NHL', division: 'Atlantic', id: 5 },
  { name: 'Florida Panthers', league: 'NHL', division: 'Atlantic', id: 26 },
  { name: 'Montreal Canadiens', league: 'NHL', division: 'Atlantic', id: 10 },
  { name: 'Ottawa Senators', league: 'NHL', division: 'Atlantic', id: 14 },
  { name: 'Tampa Bay Lightning', league: 'NHL', division: 'Atlantic', id: 20 },
  { name: 'Toronto Maple Leafs', league: 'NHL', division: 'Atlantic', id: 21 },
  // NHL — Metropolitan
  { name: 'Carolina Hurricanes', league: 'NHL', division: 'Metropolitan', id: 7 },
  { name: 'Columbus Blue Jackets', league: 'NHL', division: 'Metropolitan', id: 29 },
  { name: 'New Jersey Devils', league: 'NHL', division: 'Metropolitan', id: 11 },
  { name: 'New York Islanders', league: 'NHL', division: 'Metropolitan', id: 12 },
  { name: 'New York Rangers', league: 'NHL', division: 'Metropolitan', id: 13 },
  { name: 'Philadelphia Flyers', league: 'NHL', division: 'Metropolitan', id: 15 },
  { name: 'Pittsburgh Penguins', league: 'NHL', division: 'Metropolitan', id: 16 },
  { name: 'Washington Capitals', league: 'NHL', division: 'Metropolitan', id: 23 },
  // NHL — Central
  { name: 'Chicago Blackhawks', league: 'NHL', division: 'Central', id: 4 },
  { name: 'Colorado Avalanche', league: 'NHL', division: 'Central', id: 17 },
  { name: 'Dallas Stars', league: 'NHL', division: 'Central', id: 9 },
  { name: 'Minnesota Wild', league: 'NHL', division: 'Central', id: 30 },
  { name: 'Nashville Predators', league: 'NHL', division: 'Central', id: 27 },
  { name: 'St. Louis Blues', league: 'NHL', division: 'Central', id: 19 },
  { name: 'Utah Mammoth', league: 'NHL', division: 'Central', id: 129764 },
  { name: 'Winnipeg Jets', league: 'NHL', division: 'Central', id: 28 },
  // NHL — Pacific
  { name: 'Anaheim Ducks', league: 'NHL', division: 'Pacific', id: 25 },
  { name: 'Calgary Flames', league: 'NHL', division: 'Pacific', id: 3 },
  { name: 'Edmonton Oilers', league: 'NHL', division: 'Pacific', id: 6 },
  { name: 'Los Angeles Kings', league: 'NHL', division: 'Pacific', id: 8 },
  { name: 'San Jose Sharks', league: 'NHL', division: 'Pacific', id: 18 },
  { name: 'Seattle Kraken', league: 'NHL', division: 'Pacific', id: 124292 },
  { name: 'Vancouver Canucks', league: 'NHL', division: 'Pacific', id: 22 },
  { name: 'Vegas Golden Knights', league: 'NHL', division: 'Pacific', id: 37 },
  // Soccer — EPL
  { name: 'AFC Bournemouth', league: 'Soccer', competition: 'EPL', id: 349 },
  { name: 'Arsenal', league: 'Soccer', competition: 'EPL', id: 359 },
  { name: 'Aston Villa', league: 'Soccer', competition: 'EPL', id: 362 },
  { name: 'Brentford', league: 'Soccer', competition: 'EPL', id: 337 },
  { name: 'Brighton & Hove Albion', league: 'Soccer', competition: 'EPL', id: 331 },
  { name: 'Burnley', league: 'Soccer', competition: 'EPL', id: 379 },
  { name: 'Chelsea', league: 'Soccer', competition: 'EPL', id: 363 },
  { name: 'Crystal Palace', league: 'Soccer', competition: 'EPL', id: 384 },
  { name: 'Everton', league: 'Soccer', competition: 'EPL', id: 368 },
  { name: 'Fulham', league: 'Soccer', competition: 'EPL', id: 370 },
  { name: 'Leeds United', league: 'Soccer', competition: 'EPL', id: 357 },
  { name: 'Liverpool', league: 'Soccer', competition: 'EPL', id: 364 },
  { name: 'Manchester City', league: 'Soccer', competition: 'EPL', id: 382 },
  { name: 'Manchester United', league: 'Soccer', competition: 'EPL', id: 360 },
  { name: 'Newcastle United', league: 'Soccer', competition: 'EPL', id: 361 },
  { name: 'Nottingham Forest', league: 'Soccer', competition: 'EPL', id: 393 },
  { name: 'Sunderland', league: 'Soccer', competition: 'EPL', id: 366 },
  { name: 'Tottenham Hotspur', league: 'Soccer', competition: 'EPL', id: 367 },
  { name: 'West Ham United', league: 'Soccer', competition: 'EPL', id: 371 },
  { name: 'Wolverhampton Wanderers', league: 'Soccer', competition: 'EPL', id: 380 },
  // Soccer — La Liga
  { name: 'Alavés', league: 'Soccer', competition: 'La Liga', id: 96 },
  { name: 'Athletic Club', league: 'Soccer', competition: 'La Liga', id: 93 },
  { name: 'Atlético Madrid', league: 'Soccer', competition: 'La Liga', id: 1068 },
  { name: 'Barcelona', league: 'Soccer', competition: 'La Liga', id: 83 },
  { name: 'Celta Vigo', league: 'Soccer', competition: 'La Liga', id: 85 },
  { name: 'Elche', league: 'Soccer', competition: 'La Liga', id: 3751 },
  { name: 'Espanyol', league: 'Soccer', competition: 'La Liga', id: 88 },
  { name: 'Getafe', league: 'Soccer', competition: 'La Liga', id: 2922 },
  { name: 'Girona', league: 'Soccer', competition: 'La Liga', id: 9812 },
  { name: 'Levante', league: 'Soccer', competition: 'La Liga', id: 1538 },
  { name: 'Mallorca', league: 'Soccer', competition: 'La Liga', id: 84 },
  { name: 'Osasuna', league: 'Soccer', competition: 'La Liga', id: 97 },
  { name: 'Rayo Vallecano', league: 'Soccer', competition: 'La Liga', id: 101 },
  { name: 'Real Betis', league: 'Soccer', competition: 'La Liga', id: 244 },
  { name: 'Real Madrid', league: 'Soccer', competition: 'La Liga', id: 86 },
  { name: 'Real Oviedo', league: 'Soccer', competition: 'La Liga', id: 92 },
  { name: 'Real Sociedad', league: 'Soccer', competition: 'La Liga', id: 89 },
  { name: 'Sevilla', league: 'Soccer', competition: 'La Liga', id: 243 },
  { name: 'Valencia', league: 'Soccer', competition: 'La Liga', id: 94 },
  { name: 'Villarreal', league: 'Soccer', competition: 'La Liga', id: 102 },
  // Soccer — Serie A
  { name: 'AC Milan', league: 'Soccer', competition: 'Serie A', id: 103 },
  { name: 'AS Roma', league: 'Soccer', competition: 'Serie A', id: 104 },
  { name: 'Atalanta', league: 'Soccer', competition: 'Serie A', id: 105 },
  { name: 'Bologna', league: 'Soccer', competition: 'Serie A', id: 107 },
  { name: 'Cagliari', league: 'Soccer', competition: 'Serie A', id: 2925 },
  { name: 'Como', league: 'Soccer', competition: 'Serie A', id: 2572 },
  { name: 'Cremonese', league: 'Soccer', competition: 'Serie A', id: 4050 },
  { name: 'Fiorentina', league: 'Soccer', competition: 'Serie A', id: 109 },
  { name: 'Genoa', league: 'Soccer', competition: 'Serie A', id: 3263 },
  { name: 'Hellas Verona', league: 'Soccer', competition: 'Serie A', id: 119 },
  { name: 'Internazionale', league: 'Soccer', competition: 'Serie A', id: 110 },
  { name: 'Juventus', league: 'Soccer', competition: 'Serie A', id: 111 },
  { name: 'Lazio', league: 'Soccer', competition: 'Serie A', id: 112 },
  { name: 'Lecce', league: 'Soccer', competition: 'Serie A', id: 113 },
  { name: 'Napoli', league: 'Soccer', competition: 'Serie A', id: 114 },
  { name: 'Parma', league: 'Soccer', competition: 'Serie A', id: 115 },
  { name: 'Pisa', league: 'Soccer', competition: 'Serie A', id: 3956 },
  { name: 'Sassuolo', league: 'Soccer', competition: 'Serie A', id: 3997 },
  { name: 'Torino', league: 'Soccer', competition: 'Serie A', id: 239 },
  { name: 'Udinese', league: 'Soccer', competition: 'Serie A', id: 118 },
  // Soccer — Bundesliga
  { name: '1. FC Heidenheim 1846', league: 'Soccer', competition: 'Bundesliga', id: 6418 },
  { name: '1. FC Union Berlin', league: 'Soccer', competition: 'Bundesliga', id: 598 },
  { name: 'Bayer Leverkusen', league: 'Soccer', competition: 'Bundesliga', id: 131 },
  { name: 'Bayern Munich', league: 'Soccer', competition: 'Bundesliga', id: 132 },
  { name: 'Borussia Dortmund', league: 'Soccer', competition: 'Bundesliga', id: 124 },
  { name: 'Borussia Mönchengladbach', league: 'Soccer', competition: 'Bundesliga', id: 268 },
  { name: 'Eintracht Frankfurt', league: 'Soccer', competition: 'Bundesliga', id: 125 },
  { name: 'FC Augsburg', league: 'Soccer', competition: 'Bundesliga', id: 3841 },
  { name: 'FC Cologne', league: 'Soccer', competition: 'Bundesliga', id: 122 },
  { name: 'Hamburg SV', league: 'Soccer', competition: 'Bundesliga', id: 127 },
  { name: 'Mainz', league: 'Soccer', competition: 'Bundesliga', id: 2950 },
  { name: 'RB Leipzig', league: 'Soccer', competition: 'Bundesliga', id: 11420 },
  { name: 'SC Freiburg', league: 'Soccer', competition: 'Bundesliga', id: 126 },
  { name: 'St. Pauli', league: 'Soccer', competition: 'Bundesliga', id: 270 },
  { name: 'TSG Hoffenheim', league: 'Soccer', competition: 'Bundesliga', id: 7911 },
  { name: 'VfB Stuttgart', league: 'Soccer', competition: 'Bundesliga', id: 134 },
  { name: 'VfL Wolfsburg', league: 'Soccer', competition: 'Bundesliga', id: 138 },
  { name: 'Werder Bremen', league: 'Soccer', competition: 'Bundesliga', id: 137 },
  // Soccer — Ligue 1
  { name: 'AJ Auxerre', league: 'Soccer', competition: 'Ligue 1', id: 172 },
  { name: 'AS Monaco', league: 'Soccer', competition: 'Ligue 1', id: 174 },
  { name: 'Angers', league: 'Soccer', competition: 'Ligue 1', id: 7868 },
  { name: 'Brest', league: 'Soccer', competition: 'Ligue 1', id: 6997 },
  { name: 'Le Havre AC', league: 'Soccer', competition: 'Ligue 1', id: 3236 },
  { name: 'Lens', league: 'Soccer', competition: 'Ligue 1', id: 175 },
  { name: 'Lille', league: 'Soccer', competition: 'Ligue 1', id: 166 },
  { name: 'Lorient', league: 'Soccer', competition: 'Ligue 1', id: 273 },
  { name: 'Lyon', league: 'Soccer', competition: 'Ligue 1', id: 167 },
  { name: 'Marseille', league: 'Soccer', competition: 'Ligue 1', id: 176 },
  { name: 'Metz', league: 'Soccer', competition: 'Ligue 1', id: 177 },
  { name: 'Nantes', league: 'Soccer', competition: 'Ligue 1', id: 165 },
  { name: 'Nice', league: 'Soccer', competition: 'Ligue 1', id: 2502 },
  { name: 'Paris FC', league: 'Soccer', competition: 'Ligue 1', id: 6851 },
  { name: 'Paris Saint-Germain', league: 'Soccer', competition: 'Ligue 1', id: 160 },
  { name: 'Stade Rennais', league: 'Soccer', competition: 'Ligue 1', id: 169 },
  { name: 'Strasbourg', league: 'Soccer', competition: 'Ligue 1', id: 180 },
  { name: 'Toulouse', league: 'Soccer', competition: 'Ligue 1', id: 179 },
];
